import type { DiagramKit, ShapeDefinition } from "../registry";

export const bpmnLiteShapes: ShapeDefinition[] = [
  {
    id: "bpmn-start-event",
    family: "bpmn",
    kind: "start-event",
    displayName: "BPMN Start Event",
    description: "Process start event",
    defaultWidth: 96,
    defaultHeight: 96,
    resizePolicy: "aspect",
    portAnchors: [{ id: "out", side: "bottom", x: 0.5, y: 1 }],
    labelZones: [{ id: "main", x: 0.2, y: 0.2, width: 0.6, height: 0.6 }],
    defaultTokens: {},
    tags: ["bpmn", "event"],
    metadata: { icon: "○", legacyType: "start", renderVariant: "connector", geometry: "circle" },
  },
  {
    id: "bpmn-end-event",
    family: "bpmn",
    kind: "end-event",
    displayName: "BPMN End Event",
    description: "Process end event",
    defaultWidth: 96,
    defaultHeight: 96,
    resizePolicy: "aspect",
    portAnchors: [{ id: "in", side: "top", x: 0.5, y: 0 }],
    labelZones: [{ id: "main", x: 0.2, y: 0.2, width: 0.6, height: 0.6 }],
    defaultTokens: {},
    tags: ["bpmn", "event"],
    metadata: { icon: "◉", legacyType: "end", renderVariant: "connector", geometry: "circle" },
  },
  {
    id: "bpmn-task",
    family: "bpmn",
    kind: "task",
    displayName: "Task",
    description: "General BPMN task",
    defaultWidth: 180,
    defaultHeight: 84,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.12, y: 0.2, width: 0.76, height: 0.56 }],
    defaultTokens: {},
    tags: ["bpmn", "task"],
    metadata: { icon: "▢", legacyType: "process", renderVariant: "process", geometry: "rect" },
  },
  {
    id: "bpmn-user-task",
    family: "bpmn",
    kind: "user-task",
    displayName: "User Task",
    description: "Task performed by a human user",
    defaultWidth: 180,
    defaultHeight: 84,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.12, y: 0.2, width: 0.76, height: 0.56 }],
    defaultTokens: {},
    tags: ["bpmn", "task", "user"],
    metadata: { icon: "👤", legacyType: "process", renderVariant: "process", geometry: "rect" },
  },
  {
    id: "bpmn-service-task",
    family: "bpmn",
    kind: "service-task",
    displayName: "Service Task",
    description: "Automated service or API step",
    defaultWidth: 180,
    defaultHeight: 84,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.12, y: 0.2, width: 0.76, height: 0.56 }],
    defaultTokens: {},
    tags: ["bpmn", "task", "service"],
    metadata: { icon: "⚙", legacyType: "action", renderVariant: "action", geometry: "rect" },
  },
  {
    id: "bpmn-subprocess",
    family: "bpmn",
    kind: "subprocess",
    displayName: "Subprocess",
    description: "Collapsed BPMN subprocess",
    defaultWidth: 196,
    defaultHeight: 88,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.14, y: 0.22, width: 0.72, height: 0.5 }],
    defaultTokens: {},
    tags: ["bpmn", "subprocess"],
    metadata: { icon: "▤", legacyType: "process", renderVariant: "process", geometry: "subprocess" },
  },
  {
    id: "bpmn-exclusive-gateway",
    family: "bpmn",
    kind: "exclusive-gateway",
    displayName: "Exclusive Gateway",
    description: "Exclusive branching gateway",
    defaultWidth: 160,
    defaultHeight: 112,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out-right", side: "right", x: 1, y: 0.5 },
      { id: "out-bottom", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.22, y: 0.28, width: 0.56, height: 0.44 }],
    defaultTokens: {},
    tags: ["bpmn", "gateway"],
    metadata: { icon: "✕", legacyType: "decision", renderVariant: "decision", geometry: "diamond" },
  },
  {
    id: "bpmn-event-based-gateway",
    family: "bpmn",
    kind: "event-based-gateway",
    displayName: "Event-Based Gateway",
    description: "Waits for the first event outcome before routing",
    defaultWidth: 160,
    defaultHeight: 112,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out-right", side: "right", x: 1, y: 0.5 },
      { id: "out-bottom", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.22, y: 0.28, width: 0.56, height: 0.44 }],
    defaultTokens: {},
    tags: ["bpmn", "gateway", "event-based"],
    metadata: { icon: "◎", legacyType: "decision", renderVariant: "decision", geometry: "diamond" },
  },
  {
    id: "bpmn-parallel-gateway",
    family: "bpmn",
    kind: "parallel-gateway",
    displayName: "Parallel Gateway",
    description: "Parallel branching gateway",
    defaultWidth: 160,
    defaultHeight: 112,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out-right", side: "right", x: 1, y: 0.5 },
      { id: "out-bottom", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.22, y: 0.28, width: 0.56, height: 0.44 }],
    defaultTokens: {},
    tags: ["bpmn", "gateway"],
    metadata: { icon: "+", legacyType: "decision", renderVariant: "decision", geometry: "diamond" },
  },
  {
    id: "bpmn-inclusive-gateway",
    family: "bpmn",
    kind: "inclusive-gateway",
    displayName: "Inclusive Gateway",
    description: "Inclusive branching gateway",
    defaultWidth: 160,
    defaultHeight: 112,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out-right", side: "right", x: 1, y: 0.5 },
      { id: "out-bottom", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.22, y: 0.28, width: 0.56, height: 0.44 }],
    defaultTokens: {},
    tags: ["bpmn", "gateway"],
    metadata: { icon: "◌", legacyType: "decision", renderVariant: "decision", geometry: "diamond" },
  },
  {
    id: "bpmn-pool",
    family: "bpmn",
    kind: "pool",
    displayName: "Pool",
    description: "BPMN pool container",
    defaultWidth: 720,
    defaultHeight: 220,
    resizePolicy: "free",
    portAnchors: [],
    labelZones: [{ id: "main", x: 0.02, y: 0.1, width: 0.08, height: 0.8 }],
    defaultTokens: {},
    tags: ["bpmn", "container"],
    metadata: { icon: "▥", legacyType: "process", renderVariant: "process", geometry: "pool" },
  },
  {
    id: "bpmn-lane",
    family: "bpmn",
    kind: "lane",
    displayName: "Lane",
    description: "BPMN lane container",
    defaultWidth: 720,
    defaultHeight: 140,
    resizePolicy: "free",
    portAnchors: [],
    labelZones: [{ id: "main", x: 0.02, y: 0.1, width: 0.08, height: 0.8 }],
    defaultTokens: {},
    tags: ["bpmn", "container"],
    metadata: { icon: "▤", legacyType: "process", renderVariant: "process", geometry: "lane" },
  },
  {
    id: "bpmn-intermediate-timer-event",
    family: "bpmn",
    kind: "timer-event",
    displayName: "Intermediate Timer Event",
    description: "Intermediate wait or schedule trigger",
    defaultWidth: 104,
    defaultHeight: 104,
    resizePolicy: "aspect",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.18, y: 0.18, width: 0.64, height: 0.64 }],
    defaultTokens: {},
    tags: ["bpmn", "event", "timer"],
    metadata: { icon: "◷", legacyType: "process", renderVariant: "event", geometry: "double-circle" },
  },
  {
    id: "bpmn-intermediate-message-event",
    family: "bpmn",
    kind: "message-event",
    displayName: "Intermediate Message Event",
    description: "Intermediate message send or receive event",
    defaultWidth: 104,
    defaultHeight: 104,
    resizePolicy: "aspect",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.18, y: 0.18, width: 0.64, height: 0.64 }],
    defaultTokens: {},
    tags: ["bpmn", "event", "message"],
    metadata: { icon: "✉", legacyType: "process", renderVariant: "event", geometry: "double-circle" },
  },
  {
    id: "bpmn-intermediate-error-event",
    family: "bpmn",
    kind: "error-event",
    displayName: "Intermediate Error Event",
    description: "Intermediate error or escalation event",
    defaultWidth: 104,
    defaultHeight: 104,
    resizePolicy: "aspect",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.18, y: 0.18, width: 0.64, height: 0.64 }],
    defaultTokens: {},
    tags: ["bpmn", "event", "error"],
    metadata: { icon: "⚠", legacyType: "process", renderVariant: "event", geometry: "double-circle" },
  },
];

export const bpmnLiteKit: DiagramKit = {
  id: "bpmn-lite",
  family: "bpmn",
  displayName: "BPMN Lite",
  description: "Core BPMN events, tasks, gateways, and lane containers",
  shapeIds: bpmnLiteShapes.map((shape) => shape.id),
  edgeIds: ["bpmn-sequence-flow", "bpmn-message-flow", "bpmn-association"],
  containerIds: [],
  supportsCodeMode: true,
  supportsAutomation: true,
  supportsSwimlanes: true,
  tags: ["bpmn", "lite"],
};
