import type { DiagramKit, ShapeDefinition } from "../registry";

export const flowchartShapes: ShapeDefinition[] = [
  {
    id: "terminator-start",
    family: "flowchart",
    kind: "start-event",
    displayName: "Start",
    description: "Entry point for a process or workflow",
    defaultWidth: 180,
    defaultHeight: 64,
    resizePolicy: "content",
    portAnchors: [{ id: "out", side: "bottom", x: 0.5, y: 1 }],
    labelZones: [{ id: "main", x: 0.1, y: 0.2, width: 0.8, height: 0.6 }],
    defaultTokens: {},
    tags: ["legacy:start", "pill"],
    metadata: { icon: "▶", legacyType: "start", renderVariant: "start" },
  },
  {
    id: "process",
    family: "flowchart",
    kind: "process-step",
    displayName: "Process",
    description: "Standard work step or operation",
    defaultWidth: 180,
    defaultHeight: 64,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.1, y: 0.2, width: 0.8, height: 0.6 }],
    defaultTokens: {},
    tags: ["legacy:process", "rect"],
    metadata: { icon: "⚙", legacyType: "process", renderVariant: "process" },
  },
  {
    id: "decision",
    family: "flowchart",
    kind: "decision-gateway",
    displayName: "Decision",
    description: "Branching condition or gateway",
    defaultWidth: 180,
    defaultHeight: 120,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "yes", side: "right", x: 1, y: 0.5 },
      { id: "no", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.22, y: 0.28, width: 0.56, height: 0.44 }],
    defaultTokens: {},
    tags: ["legacy:decision", "diamond"],
    metadata: { icon: "◆", legacyType: "decision", renderVariant: "decision" },
  },
  {
    id: "action-task",
    family: "flowchart",
    kind: "automation-task",
    displayName: "Action",
    description: "Webhook, API, or automation task",
    defaultWidth: 180,
    defaultHeight: 64,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.1, y: 0.2, width: 0.8, height: 0.6 }],
    defaultTokens: {},
    tags: ["legacy:action", "automation"],
    metadata: { icon: "⚡", legacyType: "action", renderVariant: "action" },
  },
  {
    id: "terminator-end",
    family: "flowchart",
    kind: "end-event",
    displayName: "End",
    description: "Terminal outcome or end state",
    defaultWidth: 180,
    defaultHeight: 64,
    resizePolicy: "content",
    portAnchors: [{ id: "in", side: "top", x: 0.5, y: 0 }],
    labelZones: [{ id: "main", x: 0.1, y: 0.2, width: 0.8, height: 0.6 }],
    defaultTokens: {},
    tags: ["legacy:end", "pill"],
    metadata: { icon: "■", legacyType: "end", renderVariant: "end" },
  },
  {
    id: "document",
    family: "flowchart",
    kind: "document",
    displayName: "Document",
    description: "Document or report output",
    defaultWidth: 190,
    defaultHeight: 84,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.12, y: 0.18, width: 0.76, height: 0.54 }],
    defaultTokens: {},
    tags: ["legacy:process", "document"],
    metadata: { icon: "📄", legacyType: "process", renderVariant: "document" },
  },
  {
    id: "data",
    family: "flowchart",
    kind: "data-input-output",
    displayName: "Data",
    description: "Input or output data step",
    defaultWidth: 190,
    defaultHeight: 72,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.16, y: 0.22, width: 0.68, height: 0.5 }],
    defaultTokens: {},
    tags: ["legacy:process", "parallelogram"],
    metadata: { icon: "⬒", legacyType: "process", renderVariant: "data" },
  },
  {
    id: "database",
    family: "flowchart",
    kind: "database",
    displayName: "Database",
    description: "Stored or persisted data source",
    defaultWidth: 190,
    defaultHeight: 84,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.18, y: 0.22, width: 0.64, height: 0.44 }],
    defaultTokens: {},
    tags: ["legacy:process", "database"],
    metadata: { icon: "🛢", legacyType: "process", renderVariant: "database" },
  },
  {
    id: "subprocess",
    family: "flowchart",
    kind: "subprocess",
    displayName: "Subprocess",
    description: "Reusable or nested procedure",
    defaultWidth: 200,
    defaultHeight: 72,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.16, y: 0.22, width: 0.68, height: 0.5 }],
    defaultTokens: {},
    tags: ["legacy:process", "subprocess"],
    metadata: { icon: "▤", legacyType: "process", renderVariant: "subprocess" },
  },
  {
    id: "manual-input",
    family: "flowchart",
    kind: "manual-input",
    displayName: "Manual Input",
    description: "Step requiring user input",
    defaultWidth: 190,
    defaultHeight: 72,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.16, y: 0.22, width: 0.68, height: 0.5 }],
    defaultTokens: {},
    tags: ["legacy:process", "manual-input"],
    metadata: { icon: "⌨", legacyType: "process", renderVariant: "manual-input" },
  },
  {
    id: "display",
    family: "flowchart",
    kind: "display",
    displayName: "Display",
    description: "Displayed output or screen state",
    defaultWidth: 190,
    defaultHeight: 72,
    resizePolicy: "content",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.16, y: 0.22, width: 0.68, height: 0.5 }],
    defaultTokens: {},
    tags: ["legacy:process", "display"],
    metadata: { icon: "🖵", legacyType: "process", renderVariant: "display" },
  },
  {
    id: "connector",
    family: "flowchart",
    kind: "connector",
    displayName: "Connector",
    description: "On-page connector point",
    defaultWidth: 96,
    defaultHeight: 96,
    resizePolicy: "aspect",
    portAnchors: [
      { id: "in", side: "top", x: 0.5, y: 0 },
      { id: "out", side: "bottom", x: 0.5, y: 1 },
    ],
    labelZones: [{ id: "main", x: 0.2, y: 0.2, width: 0.6, height: 0.6 }],
    defaultTokens: {},
    tags: ["legacy:process", "connector"],
    metadata: { icon: "○", legacyType: "process", renderVariant: "connector" },
  },
];

export const flowchartKit: DiagramKit = {
  id: "core-flowchart",
  family: "flowchart",
  displayName: "Core Flowchart",
  description: "Standard process and logic symbols for flowcharting",
  shapeIds: flowchartShapes.map((shape) => shape.id),
  edgeIds: [],
  containerIds: [],
  supportsCodeMode: true,
  supportsAutomation: true,
  supportsSwimlanes: false,
  tags: ["flowchart", "core"],
};
